// Generated by CoffeeScript 1.6.3
(function() {
  var file_menu, file_menu_new, gui, menubar, pass1, win;

  gui = require('nw.gui');

  pass1 = require('1pass');

  win = gui.Window.get();

  menubar = new gui.Menu({
    type: 'menubar'
  });

  file_menu = new gui.Menu();

  file_menu_new = new gui.Menu();

  file_menu_new.append(new gui.MenuItem({
    label: 'Login Item',
    enabled: false
  }));

  file_menu_new.append(new gui.MenuItem({
    label: 'Wallet Item',
    checked: true,
    click: function() {
      return console.log("Wallet Item");
    }
  }));

  file_menu.append(new gui.MenuItem({
    label: 'New',
    submenu: file_menu_new
  }));

  menubar.append(new gui.MenuItem({
    label: 'File',
    submenu: file_menu
  }));

  win.menu = menubar;

  window.onresize = function(event) {
    var tbheight;
    tbheight = document.getElementById("toolbar").style.height;
    document.getElementById("sidebar").style.height = document.body.clientHeight - (tbheight + 35);
  };

}).call(this);
